// Generated by `wrangler types` — regenerate with `npx wrangler types`.
// Manual version for initial development before wrangler is installed.

interface Env {
  DB: D1Database;
  ASSETS: Fetcher;
  ALLOWED_ORIGINS: string;
  DB_NAME: string;
  SESSION_MAX_AGE_SECONDS: string;
  PASSWORD_HASH: string;
  SESSION_SECRET: string;
}
